version: '3'

services:
  mysqlserver:
    image: mysql
    container_name: mysqlserver
    env_file:
      - secrets.env
    volumes:
    - mysqldata:/var/lib/mysql
  api-services:
    container_name: api-service
    build: .
    ports:
    - 8080:80
  sql-migrations:
    container_name: sql-migrations
    build:
      context: .
      dockerfile: Dockerfile.migrations
    tty: true

volumes:
  mysqldata: